[project]
name = "func_conn_predict"
version = "0.1.0"
description = "Functional Connectivity Predction (i.e., netmats)"

[build-system]
build-backend = "flit_core.buildapi"
requires = ["flit_core >=3.2,<4"]
